version: '3.7'

services:
  nginx:
    build         :
      context: ./nginx
    image         : teamdev-web
    hostname      : teamdev-web
    container_name: teamdev-web
    depends_on    :
      - php
    ports         :
      - 80:80
    volumes       :
      - ./src:/var/www/teamdev:cached
  php:
    build         :
      context: ./phpfpm
    image         : teamdev-php
    hostname      : teamdev-php
    container_name: teamdev-php
    volumes       :
      - ./src:/var/www/teamdev:cached
  mysql:
    #restart: always
    build         :
      context: ./mysql
    image         : teamdev-db
    hostname      : teamdev-db
    container_name: teamdev-db
    volumes       :
      - ./mysql/data:/var/lib/mysql
    environment   :
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=teamdev
    ports         :
      - 3306:3306
networks:
  default:
    name: teamdev-network